apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus/serviceaccount.yaml
  - prometheus/rbac.yaml
  - prometheus/configmap-config.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - alertmanager/serviceaccount.yaml
  - alertmanager/configmap-config.yaml
  - alertmanager/deployment.yaml
  - alertmanager/service.yaml
  - grafana/serviceaccount.yaml
  - grafana/configmap-datasource.yaml
  - grafana/configmap-dashboards-provider.yaml
  - grafana/configmap-dashboard-nodes.yaml
  - grafana/configmap-dashboard-pods.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - node-exporter/serviceaccount.yaml
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  - kube-state-metrics/serviceaccount.yaml
  - kube-state-metrics/rbac.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
