apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 472
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
          emptyDir: null
