apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    azure.workload.identity/client-id: "AZURE_ALERTMANAGER_IDENTITY_CLIENT_ID"  # A REMPLACER APRES terraform apply
