apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "AZURE_ALERTMANAGER_IDENTITY_CLIENT_ID"  # A REMPLACER APRES terraform apply
    keyvaultName: "AZURE_KEY_VAULT_NAME"                # A REMPLACER APRES terraform apply
    cloudName: ""
    objects: |
      array:
        - |
          objectName: discord-webhook-url
          objectType: secret
          objectAlias: url
    tenantId: "AZURE_TENANT_ID"                         # A REMPLACER APRES terraform apply
