apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack-aks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ororck/tp-monitoring-k8s.git
    targetRevision: feat/migration-aks
    path: k8s/overlays/aks
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
